# Generated by Django 3.2.9 on 2022-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo',
            field=models.ImageField(blank=True, default='default-img.jpg', null=True, upload_to=''),
        ),
    ]
